# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Youtube_downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from ptdl.pytu import max_qldl, yt_gen
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 261)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.link_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.link_lineEdit.setObjectName("link_lineEdit")
        self.gridLayout.addWidget(self.link_lineEdit, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.max_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.max_checkBox.setCheckable(True)
        self.max_checkBox.setChecked(False)
        self.max_checkBox.setAutoRepeatDelay(300)
        self.max_checkBox.setTristate(False)
        self.max_checkBox.setObjectName("max_checkBox")
        self.verticalLayout.addWidget(self.max_checkBox)
        self.audio_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.audio_checkBox.setObjectName("audio_checkBox")
        self.verticalLayout.addWidget(self.audio_checkBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 2, 2, 1)
        self.quality_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.quality_comboBox.setObjectName("quality_comboBox")
        self.quality_comboBox.addItem("")
        self.quality_comboBox.addItem("")
        self.quality_comboBox.addItem("")
        self.quality_comboBox.addItem("")
        self.quality_comboBox.addItem("")
        self.quality_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.quality_comboBox, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.quality_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.quality_horizontalSlider.setMinimum(0)
        self.quality_horizontalSlider.setMaximum(5)
        self.quality_horizontalSlider.setProperty("value", 4)
        self.quality_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.quality_horizontalSlider.setObjectName("quality_horizontalSlider")
        self.gridLayout_2.addWidget(self.quality_horizontalSlider, 2, 0, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.place_lineEdit = QtWidgets.QLineEdit(self.splitter)
        self.place_lineEdit.setMinimumSize(QtCore.QSize(295, 0))
        self.place_lineEdit.setObjectName("place_lineEdit")
        self.edit_pushButton = QtWidgets.QPushButton(self.splitter)
        self.edit_pushButton.setMaximumSize(QtCore.QSize(84, 36))
        self.edit_pushButton.setObjectName("edit_pushButton")
        self.download_pushButton = QtWidgets.QPushButton(self.splitter)
        self.download_pushButton.setMaximumSize(QtCore.QSize(84, 36))
        self.download_pushButton.setObjectName("download_pushButton")
        self.download_pushButton.clicked.connect(self.download_click)
        self.verticalLayout_2.addWidget(self.splitter)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.quality_comboBox.setCurrentIndex(4)
        self.quality_horizontalSlider.sliderMoved['int'].connect(
            self.quality_comboBox.setCurrentIndex)  # type: ignore
        self.quality_comboBox.currentIndexChanged['int'].connect(
            self.quality_horizontalSlider.setValue)  # type: ignore
        self.max_checkBox.stateChanged['int'].connect(
            self.quality_comboBox.setCurrentIndex)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "YouTube Downloader"))
        self.label.setText(_translate("MainWindow", "Video Link"))
        self.link_lineEdit.setText(_translate(
            "MainWindow", "https://www.youtube.com"))
        self.pushButton_3.setText(_translate("MainWindow", "Enter"))
        self.max_checkBox.setText(_translate("MainWindow", "Max Quality"))
        self.max_checkBox.setShortcut(_translate("MainWindow", "Q"))
        self.audio_checkBox.setText(_translate("MainWindow", "Audio Only"))
        self.audio_checkBox.setShortcut(_translate("MainWindow", "A"))
        self.quality_comboBox.setItemText(0, _translate("MainWindow", "144p"))
        self.quality_comboBox.setItemText(1, _translate("MainWindow", "240p"))
        self.quality_comboBox.setItemText(2, _translate("MainWindow", "360p"))
        self.quality_comboBox.setItemText(3, _translate("MainWindow", "480p"))
        self.quality_comboBox.setItemText(4, _translate("MainWindow", "720p"))
        self.quality_comboBox.setItemText(5, _translate("MainWindow", "1080p"))
        self.label_2.setText(_translate("MainWindow", "Video Quality"))
        self.edit_pushButton.setText(_translate("MainWindow", "Edit"))
        self.download_pushButton.setText(_translate("MainWindow", "Download"))

    def download_click(self):
        yt, vid_tittle, vid_thumbnail = yt_gen(
            "https://www.youtube.com/watch?v=-2uyzAqefyE")
        max_qldl(yt, dl_path, vid_tittle)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
